--liquibase formatted sql

--changeset lt:external_client-drop-2
drop table if exists auth.external_client;
--

--changeset lt:external_client-2
create table auth.external_client (
  id                    bigint not null generated by default as identity primary key,
  credential            text not null unique,
  name                  text not null,
  privileges            text[] not null,
  active                bool not null default true
);
--
