--liquibase formatted sql

--changeset bob:object_storage
create table bob.object_storage (
    id              bigint not null generated by default as identity primary key,
    object_id       bigint not null,
    storage_type    text not null,
    container       text not null,
    path            text not null,
    filename        text not null,

    sys_status      char(1) default 'A' not null,
    sys_version     integer not null,
    sys_created_at  timestamptz not null,
    sys_created_by  text not null,
    sys_modified_at timestamptz,
    sys_modified_by text
);
create index bob_object_storage_object_idx on bob.object_storage(object_id);

select core.create_table_metadata('bob.object_storage');
select audit.add_log('bob.object_storage');
--
