--liquibase formatted sql

--changeset termx:task_attachment-1
create table taskforge.task_attachment (
  id                    bigint not null generated by default as identity primary key,
  task_id               bigint not null,
  file_id               text not null,
  file_name             text not null,
  description           text,
  sys_created_at        timestamp not null,
  sys_created_by        text not null,
  sys_modified_at       timestamp,
  sys_modified_by       text,
  sys_status            char(1) default 'A' not null collate "C",
  sys_version           int not null,
  constraint task_attachment_task_fkey foreign key (task_id) references taskforge.task (id)
);
create index task_attachment_task_idx on taskforge.task_attachment (task_id);

select core.create_table_metadata('taskforge.task_attachment');
select audit.add_log('taskforge.task_attachment');
--


