--liquibase formatted sql

--changeset termx:task_execution-1
create table taskforge.task_execution (
  id                    bigint not null generated by default as identity primary key,
  task_id               bigint not null,
  period_start          timestamptz,
  period_end            timestamptz,
  duration              interval,
  performer             jsonb,
  created_by            text not null,
  created_at            timestamptz not null,
  updated_at            timestamptz,
  updated_by            text,
  sys_status            char(1) default 'A' not null,
  sys_version           integer not null,
  sys_created_at        timestamptz not null,
  sys_created_by        text not null,
  sys_modified_at       timestamptz,
  sys_modified_by       text,
  constraint task_execution_task_fkey foreign key (task_id) references taskforge.task (id)
);

select core.create_table_metadata('taskforge.task_execution');
select audit.add_log('taskforge.task_execution');
--

