--liquibase formatted sql

--changeset termx:task_activity-1
create table taskforge.task_activity (
  id                    bigint not null generated by default as identity primary key,
  task_id               bigint not null,
  note                  text,
  transition            jsonb,
  context               jsonb,
  updated_by            text,
  updated_at            timestamptz,
  sys_status            char(1) default 'A' not null,
  sys_version           integer not null,
  sys_created_at        timestamptz not null,
  sys_created_by        text not null,
  sys_modified_at       timestamptz,
  sys_modified_by       text,
  constraint task_activity_task_fkey foreign key (task_id) references taskforge.task (id)
);

select core.create_table_metadata('taskforge.task_activity');
select audit.add_log('taskforge.task_activity');
--
