--liquibase formatted sql

--changeset termx:task_read_log-1
create table taskforge.task_read_log (
  id                    bigint not null generated by default as identity primary key,
  task_id               bigint not null,
  user_id               text not null,
  last_opened_time      timestamptz not null,
  sys_status            char(1) default 'A' not null,
  sys_version           integer not null,
  sys_created_at        timestamptz not null,
  sys_created_by        text not null,
  sys_modified_at       timestamptz not null,
  sys_modified_by       text not null,
  constraint task_read_log_task_fkey foreign key (task_id) references taskforge.task (id),
  constraint task_read_log_ukey unique (task_id, user_id)
);
select core.create_table_metadata('taskforge.task_read_log');
--
