--liquibase formatted sql

--changeset bob:object
create table bob.object (
    id              bigint not null generated by default as identity primary key,
    uuid            text not null,
    content_type    text,
    meta            jsonb,
    description     text,

    sys_status      char(1) default 'A' not null,
    sys_version     integer not null,
    sys_created_at  timestamptz not null,
    sys_created_by  text not null,
    sys_modified_at timestamptz,
    sys_modified_by text
);
create index bob_object_uuid_idx on bob.object(uuid);
create index bob_object_meta_idx on bob.object using gin(meta);

select core.create_table_metadata('bob.object');
select audit.add_log('bob.object');
--
