--liquibase formatted sql

--changeset wiki:template_migra-1
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:1 select count(*) from pg_catalog.pg_tables where tablename='template' and schemaname = 'thesaurus';
drop index thesaurus.template_code_ukey;
drop index thesaurus.template_content_template_idx;
--

--changeset wiki:template
drop table if exists wiki.template_content;
drop table if exists wiki.template;

create table wiki.template (
    id                  bigint not null generated by default as identity primary key,
    code                text not null,
    names               jsonb not null,
    content_type        text not null,

    sys_status          char(1) default 'A' not null,
    sys_version         integer not null,
    sys_created_at      timestamptz not null,
    sys_created_by      text not null,
    sys_modified_at     timestamptz,
    sys_modified_by     text
);
create unique index template_code_ukey on wiki.template (code) where (sys_status = 'A');

select core.create_table_metadata('wiki.template');


create table wiki.template_content (
    id                  bigint not null generated by default as identity primary key,
    template_id         bigint not null,
    lang                text not null,
    content             text not null,

    sys_status          char(1) default 'A' not null,
    sys_version         integer not null,
    sys_created_at      timestamptz not null,
    sys_created_by      text not null,
    sys_modified_at     timestamptz,
    sys_modified_by     text,

    constraint template_content_template_fk foreign key (template_id) references wiki.template(id)
);
create index template_content_template_idx on wiki.template_content(template_id);

select core.create_table_metadata('wiki.template_content');
--

--changeset wiki:template_migra-2
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:1 select count(*) from pg_catalog.pg_tables where tablename='template' and schemaname = 'thesaurus';
insert into wiki.template(id, code, names, content_type)
select id, code, names, content_type from thesaurus.template where sys_status = 'A';
select setval('wiki.template_id_seq', (select last_value from thesaurus.template_id_seq));

insert into wiki.template_content(id, template_id, lang, content)
select id, template_id, lang, content from thesaurus.template_content where sys_status = 'A';
select setval('wiki.template_content_id_seq', (select last_value from thesaurus.template_content_id_seq));
--
