--liquibase formatted sql

--changeset wiki:page
drop materialized view if exists wiki.page_link_closure;
drop table if exists wiki.page_tag;
drop table if exists wiki.page_relation;
drop table if exists wiki.page_link;
drop table if exists wiki.page_content;
drop table if exists wiki.page;

create table wiki.page (
    id                  bigint not null generated by default as identity primary key,
    status              text not null,
    space_id            bigint not null,
    settings            jsonb,

    sys_status          char(1) default 'A' not null,
    sys_version         integer not null,
    sys_created_at      timestamptz not null,
    sys_created_by      text not null,
    sys_modified_at     timestamptz,
    sys_modified_by     text,

    constraint page_space_fk foreign key (space_id) references sys.space(id)
);

select core.create_table_metadata('wiki.page');
--

--changeset wiki:page_migra-1
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:1 select count(*) from pg_catalog.pg_tables where tablename='page' and schemaname = 'thesaurus';
insert into wiki.page(id, status, space_id, settings)
select id, status, space_id, jsonb_build_object('templateId', template_id) from thesaurus.page where sys_status = 'A';
select setval('wiki.page_id_seq', (select last_value from thesaurus.page_id_seq));
--

--changeset wiki:page-code
alter table wiki.page add column code text not null default uuid_generate_v4();
alter table wiki.page add constraint page_code_excl EXCLUDE USING gist (code WITH =, space_id with =) where (sys_status='A');
--
