--liquibase formatted sql

--changeset wiki:page_relation_migra-1
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:1 select count(*) from pg_catalog.pg_tables where tablename='page_relation' and schemaname = 'thesaurus';
drop index thesaurus.page_relation_page_idx;
--

--changeset wiki:page_relation
drop table if exists wiki.page_relation;

create table wiki.page_relation (
    id                  bigint not null generated by default as identity primary key,
    page_id             bigint not null,
    content_id          bigint not null,

    type                text not null,
    target              text not null,

    sys_status          char(1) default 'A' not null,
    sys_version         integer not null,
    sys_created_at      timestamptz not null,
    sys_created_by      text not null,
    sys_modified_at     timestamptz,
    sys_modified_by     text,

    constraint page_relation_page_fk foreign key (page_id) references wiki.page(id),
    constraint page_relation_content_fk foreign key (content_id) references wiki.page_content(id)
);
create index page_relation_page_idx on wiki.page_relation(page_id);

select core.create_table_metadata('wiki.page_relation');
--


--changeset wiki:page_relation_migra-2
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:1 select count(*) from pg_catalog.pg_tables where tablename='page_relation' and schemaname = 'thesaurus';
insert into wiki.page_relation(id, page_id, content_id, type, target)
select id, page_id, content_id, type, target from thesaurus.page_relation where sys_status = 'A';
select setval('wiki.page_relation_id_seq', (select last_value from thesaurus.page_relation_id_seq));
--
