--liquibase formatted sql


--changeset wiki:page_comment-1
drop table if exists wiki.page_comment;

create table wiki.page_comment (
    id              bigint not null generated by default as identity primary key,
    page_content_id bigint not null,
    parent_id       bigint, -- for replies
    text            text,   -- selected text/quote
    comment         text not null,
    status          text not null,
    options         jsonb,

    sys_status      char(1) default 'A' not null,
    sys_version     integer not null,
    sys_created_at  timestamptz not null,
    sys_created_by  text not null,
    sys_modified_at timestamptz,
    sys_modified_by text,

    constraint page_comment_page_content_id_fk foreign key (page_content_id) references wiki.page_content(id),
    constraint page_comment_parent_fk foreign key (parent_id) references wiki.page_comment(id)
);
create index page_comment_page_content_idx on wiki.page_comment(page_content_id);
create index page_comment_parent_idx on wiki.page_comment(parent_id);

select core.create_table_metadata('wiki.page_comment');
--
