--liquibase formatted sql

--changeset kodality:provenance-2
create table sys.provenance (
  id                    bigint not null generated by default as identity primary key,
  target                jsonb not null,
  date                  timestamptz not null,
  activity              text not null,
  author                jsonb not null,
  context               jsonb,
  sys_status            char(1) default 'A' not null,
  sys_version           integer not null,
  sys_created_at        timestamptz not null,
  sys_created_by        text not null,
  sys_modified_at       timestamptz,
  sys_modified_by       text
);

select core.create_table_metadata('sys.provenance');
select audit.add_log('sys.provenance');

create index provenance_activity_idx on sys.provenance(activity);
create index provenance_target_idx on sys.provenance((target ->> 'type'), (target ->> 'id'));
create index provenance_context_idx ON sys.provenance USING GIN (context);
--
--changeset kodality:provenance-remove-audit
select audit.drop_log('sys.provenance');
--
--changeset kodality:provenance-add-detail
alter table sys.provenance add column detail jsonb;
--
