name: Weekly checks

on:
  schedule:
    # Monday 05:00 UTC
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Tests, PMD, SpotBugs, OWASP
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run checks
        working-directory: .
        run: ./gradlew check pmdCheck spotbugsCheck dependencyCheckAggregate
